baseURL = "https://human-singularity.org/"
languageCode = "en-uk"
title = "Human Singularity Network"
theme = "soft-ui"
[params]
defaultAuthor = ""
sectionPagesMenu = 'main'
[menu]
[[menu.legal]]
    name = '<strong>Tax ID</strong> PT517563363'
    pageRef = ''
